GET http://localhost:8080/hello
Accept: application/json

###

###

GET http://c002.rodeo.tacc.utexas.edu:30401/StreamsTACCDB/Proj1/_indexes
Accept: application/json

###

PUT http://c002.rodeo.tacc.utexas.edu:30401/StreamsTACCDB/Proj1/_indexes/latIndex
Content-Type: application/json

{"keys": { "document.lat": 1 } }

###

##################################### streamsTACCAdmin user #################################################
# streamsTACCAdmin   these tests are hitting the dev deployment of RH-core
#  get a collection list under StreamsTACCDB /v3/meta/StreamsTACCDB/
#  {
#    "streamsTACCAdmin": {
#      "token": "",
#      "comment": {
#        "iss": "https://dev.develop.tapis.io/v3/tokens",
#        "sub": "StreamsAdmin@dev",
#        "tapis/tenant_id": "dev",
#        "tapis/token_type": "access",
#        "tapis/delegation": false,
#        "tapis/delegation_sub": null,
#        "tapis/username": "StreamsAdmin",
#        "tapis/account_type": "service",
#        "exp": 1590920057
#      },
#      "user": "streamsTACCAdmin",
#      "tenant": "dev"
#    }
#  }

##############################################################
#      DB endpoints
##############################################################
###   db exits
GET http://localhost:8080/v3/meta/StreamsTACCDB
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###   results 200
#  [
#    "Proj1"
#  ]

###   no perms and db does not exist
GET http://localhost:8080/v3/meta/sltst
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###  results  403
#   empty response


# streamsTACCAdmin   
#  put with no arguements to StreamsTACCDB /v3/meta/StreamsTACCDB/
###
PUT http://localhost:8080/v3/meta/StreamsTACCDB
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###  results  405/500
#  ETag header is returned in headers
#  ETag: 5e4b0c95537bd1305796e5d7

# streamsTACCAdmin
#  post with no args to StreamsTACCDB /v3/meta/StreamsTACCDB/   DB already exists
###
POST http://localhost:8080/v3/meta/StreamsTACCDB
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###   results 405
#  {
#    "http status code": 405,
#    "http status description": "Method Not Allowed",
#    "message": "method POST not allowed",
#    "_links": {
#      "self": {
#        "href": "/StreamsTACCDB"
#      }
#    }
#  }

# streamsTACCAdmin
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/
#  requires the If-Match: 5d95ed1dab3cf85b199ed3b6 Header value
###
DELETE http://localhost:8080/v3/meta/testdb/
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###

##############################################################
#     Collection endpoints
##############################################################
# streamsTACCAdmin
#  get a document list under StreamsTACCDB/Proj1 /v3/meta/StreamsTACCDB/Proj1
###
GET http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###
# [
#   {
#     "_id": {
#       "$oid": "5e4bffb5a93eebf39fbecdb2"
#     },
#     "name": "instruments",
#     "_etag": {
#       "$oid": "5e4bffb5537bd1305796e5e1"
#     }
#   },
#   {
#     "_id": {
#       "$oid": "5e4bff5ea93eebf39fbecda1"
#     },
#     "name": "sites",
#     "_etag": {
#       "$oid": "5e4bff5e537bd1305796e5e0"
#     }
#   }
# ]

# streamsTACCAdmin
#  get a document list under StreamsTACCDB/Proj1 /v3/meta/StreamsTACCDB/Proj1  with a query
###
GET http://localhost:8080/v3/meta/StreamsTACCDB/Proj1?filter={'name':'test document 33'}&np=true
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###


# streamsTACCAdmin   these tests are hitting the dev deployment of RH-core
#  put with no arguements to StreamsTACCDB /v3/meta/StreamsTACCDB/
###
PUT http://localhost:8080/v3/meta/StreamsTACCDB/TstCollection
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###  result
# er ETag Header returned  ETag: 5e4c452b537bd1305796e5e2

# /v3/meta/StreamsTACCDB/TstCollection streamsTACCAdmin
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/TstCollection
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/TstCollection
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json
###  result msg with ETag header
# ETag: 5e4c452b537bd1305796e5e2
# {
#   "http status code": 409,
#   "http status description": "Conflict",
#   "message": "The ETag must be provided using the 'If-Match' header"
# }

# /v3/meta/StreamsTACCDB/TstCollection streamsTACCAdmin
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/TstCollection
#  with ETag
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/TstCollection
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
If-Match: 5e4c452b537bd1305796e5e2
Content-Type: application/json

###  result msg with ETag header
# ETag: 5e4c452b537bd1305796e5e2
# {
#   "http status code": 409,
#   "http status description": "Conflict",
#   "message": "The ETag must be provided using the 'If-Match' header"
# }


# /v3/meta/StreamsTACCDB/Proj1   streamsTACCAdmin
#  post with no args and no request body to StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
POST http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###  result 201  er  Created

# /v3/meta/StreamsTACCDB/Proj1   streamsTACCAdmin
#  post with no args and no request body to StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
POST http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

{ "name": "test document 33", "jimmyList":["1","3"],"description": "new whatever"}

###  result 201  er  Created ETag: 5e4c4e6b537bd1305796e5e4

##############################################################
#     document endpoints
##############################################################

# /v3/meta/StreamsTACCDB/Proj1/   streamsTACCAdmin
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/5e4bff5ea93eebf39fbecda1
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e4bff5ea93eebf39fbecda1
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###  result 204  er  no Content



# streamsTACCAdmin
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###  result is a 409 without ETag

# streamsTACCAdmin   these tests are hitting the dev deployment of RH-core
#  get a document from StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4 /v3/meta/StreamsTACCDB/Proj1
###
GET http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###

# streamsTACCAdmin   these tests are hitting the dev deployment of RH-core
#  put with no arguements to StreamsTACCDB /v3/meta/StreamsTACCDB/
###
PUT http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###

# streamsTACCAdmin   these tests are hitting the dev deployment of RH-core
#  post with no args to StreamsTACCDB /v3/meta/StreamsTACCDB/
###
POST http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###

# streamsTACCAdmin   these tests are hitting the dev deployment of RH-core
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streamsTACCAdmin
X-Tapis-Tenant: dev
Content-Type: application/json

###

#####################################################
#
#    Anagha test delete
#
# curl -v -X DELETE -H "X-Tapis-Token:$jwt" -H "X-Tapis-Tenant:dev" -H "X-Tapis-User: streamsTACCAdmin" http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e4bff5ea93eebf39fbecda1
#
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e4bff5ea93eebf39fbecda1
X-Tapis-Token: $jwt
X-Tapis-Tenant: dev
X-Tapis-User: streamsTACCAdmin

###








