GET http://localhost:8080/hello
Accept: application/json

###

###

GET http://c002.rodeo.tacc.utexas.edu:30401/StreamsTACCDB/Proj1/_indexes
Accept: application/json

###

PUT http://c002.rodeo.tacc.utexas.edu:30401/StreamsTACCDB/Proj1/_indexes/latIndex
Content-Type: application/json

{"keys": { "document.lat": 1 } }

###


