#  getting a master service token for meta from Tokens service with my service password
#
# curl -u "meta:{{tokPass}}" -H "Content-type: application/json" -d '{"token_tenant_id": "master", "account_type": "service", "token_username": "meta", "access_token_ttl": 9999999}' https://dev.develop.tapis.io/v3/tokens
POST https://dev.develop.tapis.io/v3/tokens
Authorization: Basic meta {{tokPass}}
Content-Type: application/json

{"token_tenant_id": "master", "account_type": "service", "token_username": "meta", "access_token_ttl": 9999999}

###  generated 4.28.2020  good till august

# {
#   "message": "Token generation successful.",
#   "result": {
#     "access_token": {
#       "access_token": "find in /scratches/1tokensAndSKpasswords.http",
#       "expires_at": "2020-08-23T12:07:04.792206+00:00",
#       "expires_in": 9999999,
#       "jti": "cad7aa58-59fa-4db4-a8ae-d6bf7ff0a3ce"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }



# get a password
# curl -H "X-Tapis-Token: $TOKENS_MASTER" -H "X-Tapis-Tenant: master" -H "X-Tapis-User: meta" 'https://dev.develop.tapis.io/v3/security/vault/secret/service/password?tenant=master&user=meta'
GET https://dev.develop.tapis.io/v3/security/vault/secret/service/password?tenant=master&user=meta
X-Tapis-Token: {{token}}
X-Tapis-Tenant: master
X-Tapis-User: meta

###

# get list of passwords
# curl -H "X-Tapis-Token: $TOKENS_MASTER" -H "X-Tapis-Tenant: master" -H "X-Tapis-User: jobs" 'https://dev.develop.tapis.io/v3/security/vault/secret/list/meta/service?tenant=master&user=jobs'
GET https://dev.develop.tapis.io/v3/security/vault/secret/list/meta/user?tenant=master&user=meta
X-Tapis-Token: {{token}}
X-Tapis-Tenant: master
X-Tapis-User: meta

###


