@startuml
!include theme/base-skin.iuml

note as N1
ResourceType
  STORAGE
  COMPUTE
- - - - - - - - - - - - -
StorageType
  POSIX
  S3
  OBJECT_STORE
- - - - - - - - - - - - -
SchedulerType
  FORK
  BATCH
  ON_DEMAND
- - - - - - - - - - - - -
SystemType
  LINUX
  WINDOWS
end note


class SGCIResource {
  schemaVersion! : string
  id! : ID
  name! : string
  description : string
  resourceType! : ResourceType
  resource! : OneOf Storage,Compute
  host :
  connection :
}

class Storage {
  storageType! : enum
  fileSystem! : FileSystem
  connection :
  capacity :
  defaultQuota :
}

class Compute {
  schedulerType! : Enum
  batchSystem! : BatchSystem
  forkSystem! : ForkSystem
  execCommands! : ExecCommand[]
  connection : Connection
}

class Host {
  host! : string
}

class Connection {
  connectionProtocol! : Enum
  securityProtocol! : Enum
  port : integer
  useProxy : boolean
  proxyHost : string
  proxyPort : integer
}

class FileSystem {
  rootDir : string
  homeDir : string
  scratchDir : string
  workDir : string
  archiveDir : string
}

class ExecCommand {
  commandType! : string
  commandPrefix : string
  homeDir : string
  moduleDependencies : string[]
}

class BatchSystem {
  jobManager! : Enum
  commandPaths : CommandPath[]
  partitions : Partition[]
}

class ForkSystem {
  systemType! : enum
  version : string
  nodeHardware : NodeHardware
}

class Partition {
  name! : string
  totalNodes : integer
  nodeHardware :
  computeQuotas :
}

class NodeHardware {
  cpuType : string
  cpuCount : integer
  gpuType : string
  gpuCount : integer
  memoryType : string
  memorySize : string
}

SGCIResource *-- "0,1" Storage : OneOf
SGCIResource *-- "0,1" Compute : OneOf
SGCIResource *-- "1" Host
SGCIResource *-- "1" Connection
Storage *-- "1" Connection
Storage *-- "1" FileSystem
Compute *-- "1" Storage
Compute *-- "0,1" BatchSystem : OneOf
Compute *-- "0,1" ForkSystem : OneOf
Compute *-- "1" Connection
Compute *-- "N" ExecCommand
BatchSystem *-- "N" Partition
Partition *-- NodeHardware
ForkSystem *-- NodeHardware

@enduml