package edu.utexas.tacc.tapis.jobs.events;

import edu.utexas.tacc.tapis.files.client.gen.model.TransferStatusEnum;
import edu.utexas.tacc.tapis.jobs.dao.JobsDao;
import edu.utexas.tacc.tapis.jobs.events.JobEventManager.SubscriptionActions;
import edu.utexas.tacc.tapis.jobs.model.Job;
import edu.utexas.tacc.tapis.jobs.model.enumerations.JobStatusType;
import edu.utexas.tacc.tapis.shared.utils.TapisGsonUtils;

/** This class generates the event detail content for all event types.  All
 * event content except for that of USER events are generated by Jobs and are
 * serialized JSON objects.  User events are created by the users who are 
 * free to format the detail data using any text format.  
 * 
 * @author rcardone
 */
public final class JobEventData 
{
    /* ********************************************************************** */
    /*                             Public Methods                             */
    /* ********************************************************************** */
    /* ---------------------------------------------------------------------- */
    /* getTransferEventData:                                                  */
    /* ---------------------------------------------------------------------- */
    static String getTransferEventData(Job job, String msg, 
                                       TransferStatusEnum transferStatus,
                                       String transactionId)
    {
        var d = new JobTransferData();
        d.setBaseFields(job, msg);
        if (transferStatus != null) d.transferStatus = transferStatus.name();
        d.transactionId = transactionId;
        return TapisGsonUtils.getGson().toJson(d);
    }
    
    /* ---------------------------------------------------------------------- */
    /* getErrorEventData:                                                     */
    /* ---------------------------------------------------------------------- */
    static String getErrorEventData(String jobUuid, String msg,
                                    JobStatusType status, JobsDao jobsDao)
    {
        // Get the name and owner from the database. The result is
        // never null but the fields contained within can be null.
        var nameOwner = jobsDao.getNameOwnerByUUIDSafe(jobUuid);
        
        var d = new JobErrorData();
        d.jobUuid  = jobUuid;
        d.jobName  = nameOwner.name;
        d.jobOwner = nameOwner.owner;
        d.message  = msg;
        if (status != null) d.jobStatus = status.name();
        return TapisGsonUtils.getGson().toJson(d);
    }
    
    /* ---------------------------------------------------------------------- */
    /* getNewStatusEventData:                                                 */
    /* ---------------------------------------------------------------------- */
    static String getNewStatusEventData(Job job, String msg, JobStatusType newStatus, 
                                        JobStatusType oldStatus)
    {
        if (newStatus != null && newStatus.isTerminal()) {
            var d = new JobTerminalStatusData();
            d.setExtendedFields(job, msg);
            d.newJobStatus = newStatus.name();
            if (oldStatus != null) d.oldJobStatus = oldStatus.name();
            return TapisGsonUtils.getGson().toJson(d);
        }
        else {
            var d = new JobNewStatusData();
            d.setBaseFields(job, msg);
            if (newStatus != null) d.newJobStatus = newStatus.name();
            if (oldStatus != null) d.oldJobStatus = oldStatus.name();
            return TapisGsonUtils.getGson().toJson(d);
        }
    }

    /* ---------------------------------------------------------------------- */
    /* getFinalEventData:                                                     */
    /* ---------------------------------------------------------------------- */
    static String getFinalEventData(Job job, String msg)
    {
        var d = new JobFinalData();
        d.setExtendedFields(job, msg);
        d.jobStatus    = job.getStatus().name();
        return TapisGsonUtils.getGson().toJson(d);
    }

    /* ---------------------------------------------------------------------- */
    /* getSubmitSubscriptionEventData:                                        */
    /* ---------------------------------------------------------------------- */
    static String getSubmitSubscriptionEventData(Job job, String msg, 
                                                   SubscriptionActions action, 
                                                   int numSubscriptions)
    {
        var d = new JobSubscriptionData();
        d.setBaseFields(job, msg);
        if (action != null) d.action = action.name();
        d.numSubscriptions = numSubscriptions;
        return TapisGsonUtils.getGson().toJson(d);
    }
    
    /* ---------------------------------------------------------------------- */
    /* getSubscriptionEventData:                                              */
    /* ---------------------------------------------------------------------- */
    static String getSubscriptionEventData(String jobUuid, String tenant, 
                                             String msg, SubscriptionActions action, 
                                             int numSubscriptions, JobsDao jobsDao)
    {
        // Get the name and owner from the database. The result is
        // never null but the fields contained within can be null.
        var nameOwner = jobsDao.getNameOwnerByUUIDSafe(jobUuid);
        
        var d = new JobSubscriptionData();
        d.jobUuid  = jobUuid;
        d.jobName  = nameOwner.name;
        d.jobOwner = nameOwner.owner;
        d.message  = msg;
        if (action != null) d.action = action.name();
        d.numSubscriptions = numSubscriptions;
        return TapisGsonUtils.getGson().toJson(d);
    }
    
    /* ---------------------------------------------------------------------- */
    /* getShareEventData:                                                     */
    /* ---------------------------------------------------------------------- */
    static String getShareEventData(String jobUuid, String tenant, String msg,
                                      String resourceType, String shareType, 
                                      String grantee, String grantor, JobsDao jobsDao)
    {
        // Get the name and owner from the database. The result is
        // never null but the fields contained within can be null.
        var nameOwner = jobsDao.getNameOwnerByUUIDSafe(jobUuid);
        
        var d = new JobShareData();
        d.jobUuid      = jobUuid;
        d.jobName      = nameOwner.name;
        d.jobOwner     = nameOwner.owner;
        d.message      = msg; 
        d.resourceType = resourceType;
        d.shareType    = shareType;
        d.grantee      = grantee;
        d.grantor      = grantor;
        return TapisGsonUtils.getGson().toJson(d);
    }
    
    /* ********************************************************************** */
    /*                          JobBaseData class                             */
    /* ********************************************************************** */
    public static class JobBaseData 
    {
        public String jobName;
        public String jobUuid;
        public String jobOwner;
        public String message;
        
        void setBaseFields(Job job, String msg)
        {
            jobName  = job.getName();
            jobUuid  = job.getUuid();
            jobOwner = job.getOwner();
            message  = msg;
        }
    }

    /* ********************************************************************** */
    /*                      JobExtendedData class                             */
    /* ********************************************************************** */
    public static class JobExtendedData
     extends JobBaseData
    {
        public int    blockedCount;
        public String remoteJobId;
        public String remoteJobId2;
        public String remoteOutcome;
        public String remoteResultInfo;
        public String remoteQueue;
        public String remoteSubmitted;
        public String remoteStarted;
        public String remoteEnded;
        
        void setExtendedFields(Job job, String msg)
        {
            setBaseFields(job, msg);
            blockedCount = job.getBlockedCount();
            remoteJobId  = job.getRemoteJobId();
            remoteJobId2 = job.getRemoteJobId2();
            if (job.getRemoteOutcome() != null) remoteOutcome = job.getRemoteOutcome().name();
            remoteResultInfo = job.getRemoteResultInfo();
            remoteQueue      = job.getRemoteQueue();
            if (job.getRemoteSubmitted() != null) remoteSubmitted = job.getRemoteSubmitted().toString();
            if (job.getRemoteStarted() != null)   remoteSubmitted = job.getRemoteStarted().toString(); 
            if (job.getRemoteEnded() != null)     remoteSubmitted = job.getRemoteEnded().toString(); 
        }
    }
    
    /* ********************************************************************** */
    /*                         JobTransferData class                          */
    /* ********************************************************************** */
    public static class JobTransferData 
     extends JobBaseData
    {
        String transferStatus;
        String transactionId;
    }

    /* ********************************************************************** */
    /*                         JobErrorData class                             */
    /* ********************************************************************** */
    public static class JobErrorData 
     extends JobBaseData
    {
       public String jobStatus;
    }
    
    /* ********************************************************************** */
    /*                         JobFinalData class                             */
    /* ********************************************************************** */
    public static class JobFinalData 
     extends JobExtendedData
   {
       public String jobStatus;
   }
    
    /* ********************************************************************** */
    /*                         JobSubscriptionData class                      */
    /* ********************************************************************** */
    public static class JobSubscriptionData 
     extends JobBaseData
    {
       public String action;
       public int    numSubscriptions;
    }
    
    /* ********************************************************************** */
    /*                        JobNewStatusData class                          */
    /* ********************************************************************** */
    public static class JobNewStatusData 
     extends JobBaseData
    {
       public String newJobStatus;
       public String oldJobStatus;
    }

    /* ********************************************************************** */
    /*                      JobTerminalStatusData class                       */
    /* ********************************************************************** */
    public static class JobTerminalStatusData 
     extends JobExtendedData
    {
       public String newJobStatus;
       public String oldJobStatus;
    }

    /* ********************************************************************** */
    /*                           JobShareData class                           */
    /* ********************************************************************** */
    public static class JobShareData 
     extends JobBaseData
    {
       public String resourceType;
       public String shareType;
       public String grantor;
       public String grantee;
    }
    
    
}
