##################################### taccMetaAdmin user #################################################
# taccMetaAdmin   these tests are hitting the dev deployment of RH-core

##############################################################
#      info endpoints
##############################################################

#   healthcheck
###  api:1
GET http://localhost:8080/v3/meta/healthcheck

###   api:1

##############################################################
#      Root endpoints
##############################################################

#   root lists DBs
###  api:1
GET http://localhost:8080/v3/meta/
X-Tapis-Token: {{token}}
X-Tapis-User: taccMetaAdmin
X-Tapis-Tenant: master
Content-Type: application/json

###   api:1

##################################### streams user #################################################
# streams   these tests are hitting the dev deployment of RH-core

##############################################################
#      DB endpoints
##############################################################

#   db exists and lists Collections
###  api:3
GET http://localhost:8080/v3/meta/StreamsDevDB
X-Tapis-Token: {{token}}
# X-JWT-Assertion-dev: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###   api:3

##############################################################
#     Collection endpoints
##############################################################

# get collection metadata
###
GET http://localhost:8080/v3/meta/StreamsTACCDB/4-2-coll-tst/_meta
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###

# create a collection in a db
###
PUT http://localhost:8080/v3/meta/StreamsTACCDB/4-2-coll-tst
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###

# delete a collection in a db
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/4-2-coll-tst
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
If-Match: 5e8dd2019e0e923a1874e332
Content-Type: application/json


###

#  get a default document list under StreamsTACCDB/Proj1 /v3/meta/StreamsTACCDB/Proj1
###
GET http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###

#  query for documents under StreamsTACCDB/Proj1 /v3/meta/StreamsTACCDB/Proj1 returns a list of documents
###
GET http://localhost:8080/v3/meta/StreamsTACCDB/Proj1?filter={'name':'test document 33'}&np=true
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###

# /v3/meta/StreamsTACCDB/Proj1   streams
# create a document in a collection
#  post with request body to StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
POST http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

{ "name": "test document 4.2-11:13", "jimmyList":["1","3"],"description": "new whatever"}

###  result 201  er  Created ETag: 5e4c4e6b537bd1305796e5e4


##############################################################
#     document endpoints
##############################################################
#  update a document
#  put with no arguements to StreamsTACCDB /v3/meta/StreamsTACCDB/
###
PUT http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###

#  get a document from StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4 /v3/meta/StreamsTACCDB/Proj1
###

GET http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###


# /v3/meta/StreamsTACCDB/Proj1/   streams
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/5e4bff5ea93eebf39fbecda1
###


DELETE http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/tstLatIndex
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###  result 204  er  no Content


##############################################################
#     Index endpoints
##############################################################
# get a list of indexes on collection
###
GET http://localhost:8080/v3/meta/StreamsTACCDB/sltCollectionTst/_indexes
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###

# create an index on collection
###
PUT http://localhost:8080/v3/meta/StreamsTACCDB/sltCollectionTst/_indexes/name1
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

{"keys": { "name": 1 } }

###

# delete an index on collection
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/sltCollectionTst/_indexes/name1
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###



# streams
#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###  result is a 409 without ETag





#  post with no args to StreamsTACCDB /v3/meta/StreamsTACCDB/
###
POST http://localhost:8080/v3/meta/StreamsTACCDB/Proj1/5e29ffe1a93eebf39fba93c4
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###


#  delete with StreamsTACCDB /v3/meta/StreamsTACCDB/
###
DELETE http://localhost:8080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant: master
Content-Type: application/json

###








