
###   db list collections
GET https://dev.develop.tapis.io/v3/meta/StreamsDevDB
X-Tapis-Token: {{token}}
Content-Type: application/json
Accept: application/json

> {%
    client.global.set("myvar","myvarvalue");
    client.log("running my global test");
    // var result = JSON.parse(response.body);
    client.log(client.global.get("myvar"));
%}

###

// basic request for document list
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
Content-Type: application/json
Accept: application/json


> {%
    var testmyvar = client.global.get("myvar");
    client.log(testmyvar);
    var result = response.body;
    // client.log(result["_id"]);
    client.log(result._etag);
%}


###