###  sanity test to see if service is alive
GET https://dev.develop.tapis.io/v3/meta/healthcheck
# X-Tapis-Token: {{token}}
# X-Tapis-User: taccMetaAdmin
# X-Tapis-Tenant: master
# Content-Type: application/json

###

##################################### meta user #################################################
# meta  these tests are hitting the dev deployment of RH-core
# run with meta.master service token settings
#
##############################################################
#      DB endpoints
##############################################################

#  HAPPY Path
###   db list collections
GET https://dev.develop.tapis.io/v3/meta/MyTstDB
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

#  HAPPY Path
###   db metadata
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/_meta
X-Tapis-Token: {{token}}
X-Tapis-User:meta
X-Tapis-Tenant:master
Content-Type: application/json

> {%
    client.test("Request MyTstDB/_meta executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

#  ERROR Path
###   no perms and db does not exist
GET https://dev.develop.tapis.io/v3/meta/sltst
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###  results  403 request for this uri path meta:dev:GET:sltst:: is NOT permitted.


#  ERROR Path
#  put with no arguements to MyTstDB /v3/meta/MyTstDB/
###
PUT https://dev.develop.tapis.io/v3/meta/MyTstDB
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###  results  200

#  ERROR Path
#  post with no args to MyTstDB /v3/meta/MyTstDB/   DB already exists
###
POST https://dev.develop.tapis.io/v3/meta/MyTstDB
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###   results 405   "Method Not Allowed"

#  TODO
#  delete with MyTstDB /v3/meta/MyTstDB/
#  requires the If-Match: 5d95ed1dab3cf85b199ed3b6 Header value
###
DELETE https://dev.develop.tapis.io/v3/meta/testdb/
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

##############################################################
#     Collection endpoints
##############################################################

#  HAPPY Path
#  get a document list under MyTstDB/MyCollection /v3/meta/MyTstDB/MyCollection
###
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

#  HAPPY Path
#  get metadata for MyTstDB/MyCollection /v3/meta/MyTstDB/MyCollection
###
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/_meta
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

#  HAPPY Path
#  get a document list under MyTstDB/MyCollection /v3/meta/MyTstDB/MyCollection  with a query
###
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection?filter={'name':'test document 33'}&np=true
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###


# metaTACCAdmin   these tests are hitting the dev deployment of RH-core
#
###
PUT https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###  result
# er ETag Header returned  ETag: 5e4c452b537bd1305796e5e2

#  get a document list under MyTstDB/MyCollection /v3/meta/MyTstDB/MyCollection  with a query
###
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/5f1892ece37f7b5a692285e9
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

# /v3/meta/MyTstDB/MyCollection metaTACCAdmin
#  delete with MyTstDB /v3/meta/MyTstDB/MyCollection
###
DELETE https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json
###  result msg with ETag header
# ETag: 5e4c452b537bd1305796e5e2
# {
#   "http status code": 409,
#   "http status description": "Conflict",
#   "message": "The ETag must be provided using the 'If-Match' header"
# }

# /v3/meta/MyTstDB/MyCollection metaTACCAdmin
#  delete with MyTstDB /v3/meta/MyTstDB/MyCollection
#  with ETag
###
DELETE https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
If-Match: 5e4c452b537bd1305796e5e2
Content-Type: application/json

###  result msg with ETag header
# ETag: 5e4c452b537bd1305796e5e2
# {
#   "http status code": 409,
#   "http status description": "Conflict",
#   "message": "The ETag must be provided using the 'If-Match' header"
# }


# /v3/meta/MyTstDB/MyCollection   metaTACCAdmin
#  post with no args and no request body to MyTstDB /v3/meta/MyTstDB/MyCollection
###
POST https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###  result 201  er  Created

# /v3/meta/MyTstDB/MyCollection   metaTACCAdmin
#  post with no args and no request body to MyTstDB /v3/meta/MyTstDB/MyCollection
###
POST https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection?basic=true
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

{ "name": "test document slt 7.21.2020-14:27", "jimmyList":["1","3"],"description": "new whatever"}

###  result 201  er  Created ETag: 5e4c4e6b537bd1305796e5e4




##############################################################
#     document endpoints
##############################################################

# /v3/meta/MyTstDB/MyCollection/   metaTACCAdmin
#  delete with MyTstDB /v3/meta/MyTstDB/5e4bff5ea93eebf39fbecda1
###
DELETE https://dev.develop.tapis.io/v3/meta/MyTstDB/Proj3/5e9de1dca93eebf39fcad799
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###  result 204  er  no Content



# metaTACCAdmin
#  delete with MyTstDB /v3/meta/MyTstDB/
###
DELETE https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###  result is a 409 without ETag

# metaTACCAdmin   these tests are hitting the dev deployment of RH-core
#  get a document from MyTstDB/MyCollection/5e29ffe1a93eebf39fba93c4 /v3/meta/MyTstDB/MyCollection
###  5e9493a5a93eebf39fc88d65
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/5e9b2a9ba93eebf39fca5508
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

# metaTACCAdmin   these tests are hitting the dev deployment of RH-core
#  put with no arguements to MyTstDB /v3/meta/MyTstDB/    # 5e29ffe1a93eebf39fba93c4
###
PUT https://dev.develop.tapis.io/v3/meta/MyTstDB/Proj3/5e8f32b1a93eebf39fc7c609
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

{ "site_name": "mysite7",
  "latitude": 1.0,
  "longitude": 2,
  "elevation": 1,
  "description": "testing replace a doc again 4.14 12.31",
  "site_id": 11
}

###

# metaTACCAdmin   these tests are hitting the dev deployment of RH-core
#  put with no arguements to MyTstDB /v3/meta/MyTstDB/    # 5e29ffe1a93eebf39fba93c4
###
PATCH https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/5e8f32b1a93eebf39fc7c609
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

{
  "description": "testing modify a doc again 4.14 12.33"
}

###

# metaTACCAdmin   these tests are hitting the dev deployment of RH-core
#  post with no args to MyTstDB /v3/meta/MyTstDB/
###
POST https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/5e8f32b1a93eebf39fc7c609
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

{ "site_name": "mysite7",
  "latitude": 1.0,
  "longitude": 2,
  "elevation": 1,
  "description": "testing update a doc 4.14 12:32",
  "site_id": 11
}

###

# metaTACCAdmin   these tests are hitting the dev deployment of RH-core
#  delete with MyTstDB /v3/meta/MyTstDB/
###
DELETE https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

#####################################################
#
#    Anagha test delete
#
# curl -v -X DELETE -H "X-Tapis-Token:$jwt" -H "X-Tapis-Tenant:dev" -H "X-Tapis-User: meta" https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/5e4bff5ea93eebf39fbecda1
#
DELETE https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/5e9b2a9ba93eebf39fca5508
X-Tapis-Token: {{token}}
X-Tapis-Tenant: master
X-Tapis-User: meta

###





# metaTACCAdmin   these tests are hitting the dev deployment of RH-core
#  get a document from MyTstDB/MyCollection/5e29ffe1a93eebf39fba93c4 /v3/meta/MyTstDB/MyCollection
###  5e9493a5a93eebf39fc88d65
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/_indexes
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###


##############################################################
#     Index endpoints
##############################################################
# get a list of indexes on collection
###
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/_indexes
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

# create an index on collection
###
PUT https://dev.develop.tapis.io/v3/meta/MyTstDB/MyCollection/_indexes/testIndex
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

{"keys": { "document.lat": 1 } }

###

# delete an index on collection
###
DELETE https://dev.develop.tapis.io/v3/meta/MyTstDB/sltCollectionTst/_indexes/name1
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

###
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/Proj3?filter={"instruments.inst_id": {"$eq":78 } }
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###

###
GET https://dev.develop.tapis.io/v3/meta/MyTstDB/Proj3?filter={"instruments.inst_id":{"$eq":78 }}&keys={"instruments.$":1}&keys={"site_id":1}
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: master
Content-Type: application/json

###


