
#  getting a master service token for meta from Tokens service with my service password
#
# curl -u "meta:{{tokPass}}" -H "Content-type: application/json" -d '{"token_tenant_id": "master", "account_type": "service", "token_username": "meta", "access_token_ttl": 9999999}' https://dev.develop.tapis.io/v3/tokens
POST https://dev.develop.tapis.io/v3/tokens
Authorization: Basic meta {{devTokPass}}
Content-Type: application/json

{"token_tenant_id": "master", "account_type": "service", "token_username": "meta", "access_token_ttl": 9999999}

###  generated 08.25.2020   good till Saturday, December 19, 2020 8:03:30 AM GMT-06:00

# {
#   "message": "Token generation successful.",
#   "result": {
#     "access_token": {
#       "access_token": ,
#       "expires_at": "2020-12-19T14:03:30.697555+00:00",
#       "expires_in": 9999999,
#       "jti": "af59668c-c05b-4497-9cd0-a621c75ee6a3"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }


# get a password
# curl -H "X-Tapis-Token: $TOKENS_MASTER" -H "X-Tapis-Tenant: master" -H "X-Tapis-User: meta" 'https://dev.develop.tapis.io/v3/security/vault/secret/service/password?tenant=master&user=meta'
GET https://dev.develop.tapis.io/v3/security/vault/secret/service/password?tenant=master&user=meta
X-Tapis-Token: {{token}}
X-Tapis-Tenant: master
X-Tapis-User: meta

###

# get list of passwords
# curl -H "X-Tapis-Token: $TOKENS_MASTER" -H "X-Tapis-Tenant: master" -H "X-Tapis-User: jobs" 'https://dev.develop.tapis.io/v3/security/vault/secret/list/meta/service?tenant=master&user=jobs'
GET https://dev.develop.tapis.io/v3/security/vault/secret/list/meta/user?tenant=master&user=meta
X-Tapis-Token: {{token}}
X-Tapis-Tenant: master
X-Tapis-User: meta

###

# curl -X POST -H "content-type: application/json" https://dev.develop.tapis.io/v3/oauth2/tokens -d '{"username": "testuser2", "password": "testuser2", "grant_type": "password"}'
POST https://dev.develop.tapis.io/v3/oauth2/tokens
Content-Type: application/json

{"username": "testuser7", "password": "testuser7", "grant_type": "password","access_token_ttl": 9999999}
###
{
  "message": "Token created successfully.",
  "result": {
    "access_token": {
      "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI3Y2UzNTA4Mi00NzFhLTRjOWMtOWZhNi02N2JlYjkwMDJhZWEiLCJpc3MiOiJodHRwczovL2Rldi5kZXZlbG9wLnRhcGlzLmlvL3YzL3Rva2VucyIsInN1YiI6InRlc3R1c2VyN0BkZXYiLCJ0YXBpcy90ZW5hbnRfaWQiOiJkZXYiLCJ0YXBpcy90b2tlbl90eXBlIjoiYWNjZXNzIiwidGFwaXMvZGVsZWdhdGlvbiI6ZmFsc2UsInRhcGlzL2RlbGVnYXRpb25fc3ViIjpudWxsLCJ0YXBpcy91c2VybmFtZSI6InRlc3R1c2VyNyIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDM3NTMyNDcsInRhcGlzL2NsaWVudF9pZCI6bnVsbCwidGFwaXMvZ3JhbnRfdHlwZSI6InBhc3N3b3JkIn0.Ye725dyR8pzdEDoek3v28hgPGNl2RJwZqXjFkbO7RTxIlNVg67t7dKMpmY_cG9o_kLxk8RRCRTzybR-Dke2Pb6tCCzyZGLkk4HMqkxhEnTiwrRtduzU5SMbF1W70xg69cN5SWYKizJn57mSBV0P9QqFgyQKeSyKp59gbI5ZSXdXfi9OoxO66TVHmzpLqqjCJ_UJhrH_7M7btV9SE1TXn4MdvigNzSbN7N0BAJgpgvRWw8ag8-uRCjIJiGDWoayu6pQD8MO5ov3WFqPXBiCfqXi6fMS49DMMRH6uZ_Gc3sR1ObgPINb0PMG8vvGVDlCv4PTo2Q3uovJheqlzvQ2mf5w",
      "expires_at": "2020-10-26T23:00:47.139074+00:00",
      "expires_in": 14400,
      "jti": "7ce35082-471a-4c9c-9fa6-67beb9002aea"
    }
  },
  "status": "success",
  "version": "dev"
}



# {
#   "message": "Token created successfully.",
#   "result": {
#     "access_token": {
#       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJmZTVhODI5Yy0wM2JhLTQ0OWEtOGZlNC0zOTIzOTQxMDllNzEiLCJpc3MiOiJodHRwczovL2Rldi5kZXZlbG9wLnRhcGlzLmlvL3YzL3Rva2VucyIsInN1YiI6InRlc3R1c2VyN0BkZXYiLCJ0YXBpcy90ZW5hbnRfaWQiOiJkZXYiLCJ0YXBpcy90b2tlbl90eXBlIjoiYWNjZXNzIiwidGFwaXMvZGVsZWdhdGlvbiI6ZmFsc2UsInRhcGlzL2RlbGVnYXRpb25fc3ViIjpudWxsLCJ0YXBpcy91c2VybmFtZSI6InRlc3R1c2VyNyIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE1ODg4OTI3MTksInRhcGlzL2NsaWVudF9pZCI6bnVsbCwidGFwaXMvZ3JhbnRfdHlwZSI6InBhc3N3b3JkIn0.cb0tRoFHrvHJaKTEBojHckMvunv8bzmD07vY4GJo66Ml8Cg1MyoeD_Z-Wf2Z0MdG49Rvb3MMjEc5BLHi9qzzfAIXIcNuRhrR6QLKyPnoX_IbHWWCVh7yesnH0bIZhjygsNnLVl9llcmV9fWGYPzPh8quVdJccFw2pLneqGzxe0mLI7xfFcCL_5zNYpqj2JzM17yVj6e9vKI8qDrJzAT_jZgtNepy07ujbBbQ32-nuvMiJlygbiVxJvWzbxsv87T0UcZ_wZyw5bR8ngJhenYL6WxfXz21m4gif-bElpaNrdAHMTyMvwR_l9IX366SzZe2fN5_rs7yHxFrFH2R_g3Upg",
#       "expires_at": "2020-05-07T23:05:19.943175+00:00",
#       "expires_in": 14400,  # 4 hrs
#       "jti": "fe5a829c-03ba-449a-8fe4-392394109e71"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }


