package edu.utexas.tacc.tapis.systems.client;

/**
 * Class providing a convenient front-end for the automatically generated client code
 * for the Systems Service REST API.
 * Underlying client classes with "gen" in the package name are generated by
 * openapi-generator each time a build is run.
 */
public class SystemsClient
{
    /* **************************************************************************** */
    /*                                   Constants                                  */
    /* **************************************************************************** */

    /* **************************************************************************** */
    /*                                 Constructors                                 */
    /* **************************************************************************** */
    public SystemsClient() {}
    
    /* **************************************************************************** */
    /*                                Public Methods                                */
    /* **************************************************************************** */
}
