
#  getting a Master Service token for meta from Tokens service with my service password
#
# curl -u "meta:{{tokPass}}" -H "Content-type: application/json" -d '{"token_tenant_id": "master", "account_type": "service", "token_username": "meta", "access_token_ttl": 9999999}' https://master.staging.tapis.io/v3/tokens
###
POST https://master.staging.tapis.io/v3/tokens
Authorization: Basic meta {{stageTokPass}}
Content-Type: application/json

{
  "token_tenant_id": "master",
  "account_type": "service",
  "token_username": "meta",
  "access_token_ttl": 9999999,
  "target_site_id": "tacc"
}

###
# {
#   "message": "Token generation successful.",
#   "result": {
#     "access_token": {
#       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI4M2VjZDc1ZS0xODcwLTRjNmQtYmZiZS00ODBmY2QxMTRkNzIiLCJpc3MiOiJodHRwczovL21hc3Rlci5zdGFnaW5nLnRhcGlzLmlvL3YzL3Rva2VucyIsInN1YiI6Im1ldGFAbWFzdGVyIiwidGFwaXMvdGVuYW50X2lkIjoibWFzdGVyIiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJtZXRhIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTYxNTAzODQxNCwidGFwaXMvdGFyZ2V0X3NpdGUiOiJ0YWNjIn0.fOMkz3ydDnNiUGf-xOFUS6mkFsTWAdqERfRWrvm0FJD4p_roMOzsPH38H-06kcgnYRhGhFi9fgy1Y3_GKxLmM2ntwfLpQujg1M7g_G1NcE1umF9TEA7t7j7Ag_gKjdO-ldKt0EqXSdy3vll4LJNQ-XrfbRshDkD2YIBoHCgCjl2rd9Hg_vjoy53x2-fk_Nn9ocLInqUWEYqYznErDo8c23cXVm1XA8FC2gtrgYhPqWeRj_FpvLac5-YG_6mHoA6SkiZHEazAiyb8oNwkWXocKcT8mZ2d5X84J58fpR3UmRWC7GRmge4Kq3FiSG6-KJw9TgIqWPB4xZW18XFNakskmw",
#       "expires_at": "2021-03-06T13:46:54.055315+00:00",
#       "expires_in": 9999999,
#       "jti": "83ecd75e-1870-4c6d-bfbe-480fcd114d72"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }

# get a password
# curl -H "X-Tapis-Token: $TOKENS_MASTER" -H "X-Tapis-Tenant: master" -H "X-Tapis-User: meta" 'https://master.staging.tapis.io/v3/security/vault/secret/service/password?tenant=master&user=meta'
GET https://master.staging.tapis.io/v3/security/vault/secret/service/password?tenant=master&user=meta
X-Tapis-Token: {{stageTokPass}}
X-Tapis-Tenant: master
X-Tapis-User: meta

###

# get list of passwords
# curl -H "X-Tapis-Token: $TOKENS_MASTER" -H "X-Tapis-Tenant: master" -H "X-Tapis-User: jobs" 'https://master.staging.tapis.io/v3/security/vault/secret/list/meta/service?tenant=master&user=jobs'
GET https://master.staging.tapis.io/v3/security/vault/secret/list/meta/user?tenant=master&user=meta
X-Tapis-Token: {{token}}
X-Tapis-Tenant: master
X-Tapis-User: meta

###

# curl -X POST -H "content-type: application/json" https://master.staging.tapis.io/v3/oauth2/tokens -d '{"username": "testuser2", "password": "testuser2", "grant_type": "password"}'
POST https://master.staging.tapis.io/v3/oauth2/tokens
Content-Type: application/json

{
  "username": "testuser7",
  "password": "testuser7",
  "grant_type": "password"
}

###

# {
#   "message": "Token created successfully.",
#   "result": {
#     "access_token": {
#       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJmZTVhODI5Yy0wM2JhLTQ0OWEtOGZlNC0zOTIzOTQxMDllNzEiLCJpc3MiOiJodHRwczovL2Rldi5kZXZlbG9wLnRhcGlzLmlvL3YzL3Rva2VucyIsInN1YiI6InRlc3R1c2VyN0BkZXYiLCJ0YXBpcy90ZW5hbnRfaWQiOiJkZXYiLCJ0YXBpcy90b2tlbl90eXBlIjoiYWNjZXNzIiwidGFwaXMvZGVsZWdhdGlvbiI6ZmFsc2UsInRhcGlzL2RlbGVnYXRpb25fc3ViIjpudWxsLCJ0YXBpcy91c2VybmFtZSI6InRlc3R1c2VyNyIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE1ODg4OTI3MTksInRhcGlzL2NsaWVudF9pZCI6bnVsbCwidGFwaXMvZ3JhbnRfdHlwZSI6InBhc3N3b3JkIn0.cb0tRoFHrvHJaKTEBojHckMvunv8bzmD07vY4GJo66Ml8Cg1MyoeD_Z-Wf2Z0MdG49Rvb3MMjEc5BLHi9qzzfAIXIcNuRhrR6QLKyPnoX_IbHWWCVh7yesnH0bIZhjygsNnLVl9llcmV9fWGYPzPh8quVdJccFw2pLneqGzxe0mLI7xfFcCL_5zNYpqj2JzM17yVj6e9vKI8qDrJzAT_jZgtNepy07ujbBbQ32-nuvMiJlygbiVxJvWzbxsv87T0UcZ_wZyw5bR8ngJhenYL6WxfXz21m4gif-bElpaNrdAHMTyMvwR_l9IX366SzZe2fN5_rs7yHxFrFH2R_g3Upg",
#       "expires_at": "2020-05-07T23:05:19.943175+00:00",
#       "expires_in": 14400,  # 4 hrs
#       "jti": "fe5a829c-03ba-449a-8fe4-392394109e71"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }


