######################################################
#   staging calls
#   tests with meta:master service token
#
######################################################

# SK grant permission for a user mlm55  all operations for jplDB
### SK grant permission for a user mpackard all operations for jplDB
POST https://master.tapis.io/v3/security/user/grantUserPermission?tenant=tacc
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"mlm55","tenant":"tacc","permSpec":"meta:tacc:GET,POST,PUT,PATCH,DELETE:jplDB:*:*"}

###

### SK grant permission for a user meta all operations except delete
POST https://master.tapis.io/v3/security/user/grantUserPermission?tenant=master
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streams","tenant":"master","permSpec":"meta:master:GET,POST,PUT,PATCH,DELETE:StreamsTACCDB:*:*"}

###

### SK grant permission for a user meta all operations except delete
POST https://masterd.tapis.io/v3/security/user/grantUserPermission?tenant=master
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"meta","tenant":"master","permSpec":"meta:master:GET,POST,PUT,PATCH,DELETE:*:*:*"}

###

### SK get permissions for user using meta:master service token
GET https://master.tapis.io/v3/security/user/perms/mpackard?tenant=tacc
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

###





######################################################
#   legacy for dev
#   tests with taccMetaAdmin:master service token
#
######################################################

x
### SK isPermitted for user
POST https://dev.develop.tapis.io/v3/security/user/isPermitted?tenant=master
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streams","tenant":"dev","permSpec":"meta:master:GET:StreamsTACCDB:*:*"}

###
# true
# {"user":"streamsTACCAdmin","tenant":"dev","permSpec":"meta:dev:GET:StreamsTACCDB:*:*"}

#
# {"user":"taccMetaAdmin","tenant":"dev","permSpec":"meta:dev:GET:::"}



### SK grant permission for a taccMetaAdmin to all operations
POST https://dev.develop.tapis.io/v3/security/user/grantUserPermission?tenant=master
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"meta","tenant":"master","permSpec":"meta:master:GET,POST,PUT,PATCH,DELETE:::"}

###


### SK grant permission for a user meta all operations except delete
POST https://dev.develop.tapis.io/v3/security/user/grantUserPermission?tenant=master
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streams","tenant":"master","permSpec":"meta:master:GET,POST,PUT,PATCH,DELETE:StreamsTACCDB:*:*"}

###

### SK isPermitted for a user
POST https://dev.develop.tapis.io/v3/security/user/isPermitted
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"meta","tenant":"master","permSpec":"meta:master:GET:StreamsTACCDB::"}

###

# GET, POST and PUT ops on everything below slttestdb but DELETE

### SK revoke permission for a user streamsTACCAdmin
POST https://dev.develop.tapis.io/v3/security/user/revokeUserPermission
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"taccMetaAdmin","tenant":"master","permSpec":"meta:dev:GET,POST,PUT,DELETE:*:*:*"}

###
#      "meta:dev:DELETE:*:1collection:slttestdb",
#      "meta:dev:DELETE::somecollection:slttestdb",
#      "meta:dev:GET,POST,PUT:*:*:slttestdb"
############################################
#
#     general tests
#
############################################

### SK hello
# curl -H "X-Tapis-Token: $USER_JWT" "http://c002.rodeo.tacc.utexas.edu:32169/security/v3/hello?pretty=true"
GET {{host}}/hello?pretty=true
X-Tapis-Token: {{token}}

###

### SK get role names
# curl -H "X-Tapis-Token: $USER_JWT" "http://c002.rodeo.tacc.utexas.edu:32169/security/v3/hello?pretty=true"
GET {{host}}/role?pretty=true
X-Tapis-Token: {{token}}

###

### create a new role to use
# curl -X POST "http://c002.rodeo.tacc.utexas.edu:32169/security/v3/role?pretty=true" -H "X-Tapis-Token: $USER_JWT" -d "{\"roleName\":\"myrole1\",\"description\":\"this is a description\"}"
POST {{host}}/role?pretty=true
X-Tapis-Token: {{token}}
Content-Type: application/json

{"roleName":"vdjUser","description":"the normal user role for VDJ server"}

###

### query if user has the role
# curl -X POST "http://c002.rodeo.tacc.utexas.edu:32169/security/v3/role?pretty=true" -H "X-Tapis-Token: $USER_JWT" -d "{\"roleName\":\"myrole1\",\"description\":\"this is a description\"}"
POST https://dev.develop.tapis.io/v3/security/user/hasRole?pretty=true
X-Tapis-Token: {{token}}
Content-Type: application/json

{"user":"vdjuser","roleName":"vdjUser"}
###

### list user roles
# curl -X POST "http://c002.rodeo.tacc.utexas.edu:32169/security/v3/role?pretty=true" -H "X-Tapis-Token: $USER_JWT" -d "{\"roleName\":\"myrole1\",\"description\":\"this is a description\"}"
GET {{host}}/user/roles/{{user}}?pretty=true
X-Tapis-Token: {{token}}
Content-Type: application/json

###


### grant role to user
# curl -X POST "http://c002.rodeo.tacc.utexas.edu:32169/security/v3/role?pretty=true" -H "X-Tapis-Token: $USER_JWT" -d "{\"roleName\":\"myrole1\",\"description\":\"this is a description\"}"
POST {{host}}/user/grantRole?pretty=true
X-Tapis-Token: {{token}}
Content-Type: application/json

{"user":"sterry1","roleName":"vdjAdmin"}
###

### SK get role names
GET {{host}}/role?pretty=true
X-Tapis-Token: {{token}}

###

### SK get permissions for a sterry1
GET https://dev.develop.tapis.io/v3/security/user/perms/sterry1
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

  {"user":"sterry1","permSpec":"meta:dev:*"}

###

### SK set permission for a user sterry1
POST https://dev.develop.tapis.io/v3/security/user/grantUserPermission
X-Tapis-Token: {{token}}
Content-Type: application/json

{"user":"sterry1","permSpec":"meta:dev:*"}

###

### SK revoke permission for a user streamsTACCAdmin
POST https://dev.develop.tapis.io/v3/security/user/revokeUserPermission
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streamsTACCAdmin","permSpec":"meta:dev:GET,POST,PUT:/StreamsTACCDB"}

###

### SK isPermitted for a user
POST https://dev.develop.tapis.io/v3/security/user/isPermitted
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streamsTACCAdmin","permSpec":"meta:dev:POST:/StreamsTACCDB/Proj1"}

###

### list user streamsTACCAdmin roles
GET https://dev.develop.tapis.io/v3/security/user/roles/streamsTACCAdmin
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

###



############################################
#
#     tests with streamsTACCAdmin and StreamsTACCDB
#
############################################

### SK get permissions for streamsTACCAdmin
GET https://dev.develop.tapis.io/v3/security/user/perms/streamsTACCAdmin
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

###

### SK grant permission
# for a user streamsTACCAdmin all operations including delete
POST https://dev.develop.tapis.io/v3/security/user/grantUserPermission
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streamsTACCAdmin","permSpec":"meta:dev:GET,PUT,POST,DELETE:testdb:*:*"}

###


### SK isPermitted for a user
POST https://dev.develop.tapis.io/v3/security/user/isPermitted
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streamsTACCAdmin","permSpec":"meta:dev:DELETE:StreamsTACCDB::"}

###

# GET, POST and PUT ops on everything below slttestdb but DELETE


### SK revoke permission for a user streamsTACCAdmin
POST https://dev.develop.tapis.io/v3/security/user/revokeUserPermission
X-Tapis-Token: {{token}}
X-Tapis-User: {{user}}
X-Tapis-Tenant:{{tenant}}
Content-Type: application/json

{"user":"streamsTACCAdmin","permSpec":"meta:dev:DELETE:StreamsTACCDB:*:*"}

###


